version: '3'

services:
  app:
    build: .
    command: npm run start
    image: lera/web-app
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - "db:db"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12354
      - POSTGRES_USER=lera
      - POSTGRES_DB=users